version: "3.8"
services:
  wg-easy:
    env_file:
      - .env
    build:
      context: wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
